### ISSUE TITLE
Leave a comment

### ISSUE THREAD

**Issue by oatsandchocolate** [alexaverill/FamilyRecipeApp#8]

**Comment by alexaverill** [comment]
Need to add a WYSIWYG Editor view and store alongside recipe Leaning towards React Mui Draft https://kelsier90.github.io/react-mui-draft-wysiwyg/examples/display-content-in-your-page

**Comment by alexaverill** [comment]
react-mui-draft is no longer supported for new versions of MUI, going to try react-quill instead https://www.npmjs.com/package/react-quill
